# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='userpb',
  syntax='proto3',
  serialized_pb=_b('\n\nuser.proto\x12\x06userpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\x1c\n\x0cUsersRequest\x12\x0c\n\x04name\x18\x01 \x03(\t\"s\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1e\n\x06gender\x18\x03 \x01(\x0e\x32\x0e.userpb.Gender\x12)\n\x05\x62irth\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*+\n\x06Gender\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x02\x32z\n\x04User\x12\x36\n\x07GetUser\x12\x13.userpb.UserRequest\x1a\x14.userpb.UserResponse\"\x00\x12:\n\x08GetUsers\x12\x14.userpb.UsersRequest\x1a\x14.userpb.UserResponse\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='userpb.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=229,
  serialized_end=272,
)
_sym_db.RegisterEnumDescriptor(_GENDER)

Gender = enum_type_wrapper.EnumTypeWrapper(_GENDER)
UNKNOWN = 0
MALE = 1
FEMALE = 2



_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='userpb.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='userpb.UserRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=80,
)


_USERSREQUEST = _descriptor.Descriptor(
  name='UsersRequest',
  full_name='userpb.UsersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='userpb.UsersRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=110,
)


_USERRESPONSE = _descriptor.Descriptor(
  name='UserResponse',
  full_name='userpb.UserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='userpb.UserResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='userpb.UserResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='userpb.UserResponse.gender', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='birth', full_name='userpb.UserResponse.birth', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=227,
)

_USERRESPONSE.fields_by_name['gender'].enum_type = _GENDER
_USERRESPONSE.fields_by_name['birth'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['UsersRequest'] = _USERSREQUEST
DESCRIPTOR.message_types_by_name['UserResponse'] = _USERRESPONSE
DESCRIPTOR.enum_types_by_name['Gender'] = _GENDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERREQUEST,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:userpb.UserRequest)
  ))
_sym_db.RegisterMessage(UserRequest)

UsersRequest = _reflection.GeneratedProtocolMessageType('UsersRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERSREQUEST,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:userpb.UsersRequest)
  ))
_sym_db.RegisterMessage(UsersRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERRESPONSE,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:userpb.UserResponse)
  ))
_sym_db.RegisterMessage(UserResponse)



_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='userpb.User',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=274,
  serialized_end=396,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUser',
    full_name='userpb.User.GetUser',
    index=0,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_USERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUsers',
    full_name='userpb.User.GetUsers',
    index=1,
    containing_service=None,
    input_type=_USERSREQUEST,
    output_type=_USERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class UserStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetUser = channel.unary_unary(
          '/userpb.User/GetUser',
          request_serializer=UserRequest.SerializeToString,
          response_deserializer=UserResponse.FromString,
          )
      self.GetUsers = channel.unary_stream(
          '/userpb.User/GetUsers',
          request_serializer=UsersRequest.SerializeToString,
          response_deserializer=UserResponse.FromString,
          )


  class UserServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetUser(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetUser': grpc.unary_unary_rpc_method_handler(
            servicer.GetUser,
            request_deserializer=UserRequest.FromString,
            response_serializer=UserResponse.SerializeToString,
        ),
        'GetUsers': grpc.unary_stream_rpc_method_handler(
            servicer.GetUsers,
            request_deserializer=UsersRequest.FromString,
            response_serializer=UserResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'userpb.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaUserServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetUser(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetUsers(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaUserStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetUser(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetUser.future = None
    def GetUsers(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_User_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('userpb.User', 'GetUser'): UserRequest.FromString,
      ('userpb.User', 'GetUsers'): UsersRequest.FromString,
    }
    response_serializers = {
      ('userpb.User', 'GetUser'): UserResponse.SerializeToString,
      ('userpb.User', 'GetUsers'): UserResponse.SerializeToString,
    }
    method_implementations = {
      ('userpb.User', 'GetUser'): face_utilities.unary_unary_inline(servicer.GetUser),
      ('userpb.User', 'GetUsers'): face_utilities.unary_stream_inline(servicer.GetUsers),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_User_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('userpb.User', 'GetUser'): UserRequest.SerializeToString,
      ('userpb.User', 'GetUsers'): UsersRequest.SerializeToString,
    }
    response_deserializers = {
      ('userpb.User', 'GetUser'): UserResponse.FromString,
      ('userpb.User', 'GetUsers'): UserResponse.FromString,
    }
    cardinalities = {
      'GetUser': cardinality.Cardinality.UNARY_UNARY,
      'GetUsers': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'userpb.User', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
